import React from 'react'

const BackgroundContext = React.createContext({
  isDarkMode: false,
  savedVideos: [],
  likedVideos: [],
  dislikedVideos: [],
  historyVideos: [],
  authToken: '',
  activeUserKey: '',
  isUserDataLoading: false,
  toggleTheme: () => {},
  toggleSaveVideo: async () => false,
  likeVideo: async () => false,
  dislikeVideo: async () => null,
  removeLike: async () => false,
  addToHistory: async () => false,
  refreshHistory: async () => {},
  getHistoryVideos: async () => {},
  clearHistoryVideos: async () => false,
  removeSavedVideo: async () => false,
  removeHistoryVideo: async () => false,
  removeLikedVideo: async () => false,
  removeDislikedVideo: async () => false,
  getSavedVideos: async () => {},
  addSavedVideo: async () => false,
  getLikedVideos: async () => {},
  addLikedVideo: async () => false,
  getDislikedVideos: async () => {},
  toggleDislikedVideo: async () => null,
  setAuthenticatedUser: () => {},
  logoutUser: () => {},
  bootstrapUserData: async () => {},
})

export default BackgroundContext
